export const STORITVE = [
  "Gradnja & adaptacije",
  "Vodovod & ogrevanje",
  "Elektrika & pametni sistemi",
  "Mizarstvo & kovinarstvo",
  "Zaključna dela",
  "Okna, vrata & senčila",
  "Okolica & zunanja ureditev",
  "Vzdrževanje & popravila",
  "Poslovne storitve",
  "Drugo",
] as const

export const LOKACIJE = [
  "Ljubljana",
  "Maribor",
  "Celje",
  "Kranj",
  "Koper",
  "Novo Mesto",
  "Velenje",
  "Murska Sobota",
  "Ptuj",
  "Kamnik",
  "Domžale",
  "Škofja Loka",
  "Trbovlje",
  "Krško",
  "Postojna",
  "Slovenj Gradec",
  "Jesenice",
  "Nova Gorica",
  "Brežice",
  "Izola",
] as const
