-- Add instant offer support and marketplace columns
-- This migration adds the missing columns for instant offer functionality

-- 1. Add columns to obrtnik_profiles for instant offers
ALTER TABLE obrtnik_profiles
  ADD COLUMN IF NOT EXISTS enable_instant_offers BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS instant_offer_templates JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS plan_type TEXT DEFAULT 'START' CHECK (plan_type IN ('START', 'PRO')),
  ADD COLUMN IF NOT EXISTS referral_code VARCHAR(20) UNIQUE;

-- 2. Update ponudbe status to include all statuses
-- First drop the old constraint
ALTER TABLE ponudbe
  DROP CONSTRAINT IF EXISTS ponudbe_status_check;

-- Then add the new constraint with all statuses
ALTER TABLE ponudbe
  ADD CONSTRAINT ponudbe_status_check CHECK (status IN ('draft', 'poslana', 'sprejeta', 'zavrnjena', 'preklicana'));

-- 3. Add auto-generated and template_id columns if they don't exist
ALTER TABLE ponudbe
  ADD COLUMN IF NOT EXISTS auto_generated BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS template_id UUID;

-- 4. Create marketplace_events table for audit trail
CREATE TABLE IF NOT EXISTS marketplace_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_type TEXT NOT NULL CHECK (
    event_type IN (
      'request_created',
      'matched',
      'broadcast_sent_matched',
      'broadcast_sent_deadline_warning',
      'broadcast_sent_offer_accepted',
      'instant_offer',
      'offer_accepted',
      'expired',
      'guarantee_activated'
    )
  ),
  request_id UUID NOT NULL REFERENCES povprasevanja(id) ON DELETE CASCADE,
  partner_id UUID REFERENCES obrtnik_profiles(id) ON DELETE SET NULL,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for marketplace_events
CREATE INDEX IF NOT EXISTS idx_marketplace_events_request_id
  ON marketplace_events(request_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_marketplace_events_partner_id
  ON marketplace_events(partner_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_marketplace_events_type
  ON marketplace_events(event_type, created_at DESC);

-- Row-level security for marketplace_events (service role only)
ALTER TABLE marketplace_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY IF NOT EXISTS marketplace_events_service_only
  ON marketplace_events
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- 5. Add comments for clarity
COMMENT ON COLUMN obrtnik_profiles.enable_instant_offers IS 'Whether the craftsman has enabled instant offers functionality';
COMMENT ON COLUMN obrtnik_profiles.instant_offer_templates IS 'JSON array of offer templates for auto-generation';
COMMENT ON COLUMN obrtnik_profiles.plan_type IS 'Subscription plan: START or PRO';
COMMENT ON COLUMN ponudbe.status IS 'Status: draft (not sent), poslana (sent), sprejeta (accepted), zavrnjena (rejected), preklicana (cancelled)';
COMMENT ON COLUMN ponudbe.auto_generated IS 'Whether the offer was auto-generated by the system';
COMMENT ON COLUMN ponudbe.template_id IS 'Reference to the template used for auto-generation';
COMMENT ON TABLE marketplace_events IS 'Audit trail for all marketplace lifecycle events';
